# Generated by Django 4.2.3 on 2023-07-27 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0002_tag_produit_tag"),
        ("commande", "0002_commande_client_commande_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.CreateModel(
            name="Prod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produit.produit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ManyToManyField(to="commande.prod"),
        ),
    ]
