# Generated by Django 4.2.3 on 2023-07-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0002_tag_produit_tag"),
        ("commande", "0003_remove_commande_produit_prod_commande_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.DeleteModel(
            name="Prod",
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produit.produit",
            ),
        ),
    ]
