# Generated by Django 4.2.3 on 2023-07-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0002_tag_produit_tag"),
        ("commande", "0004_remove_commande_produit_delete_prod_commande_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produit",
        ),
        migrations.AddField(
            model_name="commande",
            name="produits",
            field=models.ManyToManyField(to="produit.produit"),
        ),
    ]
